server {
    listen 3008;
    root /usr/share/nginx/html;
    index index.html;

    # Evitar redirecciones con puerto
    port_in_redirect off;
    absolute_redirect off;

    location / {
        try_files $uri $uri/ /monitoreo_vmt/index.html /index.html;
    }

    location /monitoreo_vmt/ {
        alias /usr/share/nginx/html/monitoreo_vmt/;
        try_files $uri $uri/ /monitoreo_vmt/index.html;
    }


    # Proxies para el API (siguiendo tu ejemplo funcional)

    location /api/ {
        proxy_pass http://backend:8010/;
    }

    location /monitoreo_vmt/api/ {
        proxy_pass http://backend:8010/;
    }
}
