server {
    listen 3003;
    server_name _;

    # Desactivar TODO tipo de redirección absoluta o con puerto
    port_in_redirect off;
    absolute_redirect off;
    server_name_in_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    # Servir archivos del frontend
    location /monitoreo_vmt/ {
        try_files $uri $uri/ /monitoreo_vmt/index.html;
    }

    # El API puente
    location /monitoreo_vmt/api/ {
        proxy_pass http://backend:8010/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Si por error llega a la raíz, intentar servir desde la subcarpeta sin redirigir
    location / {
        try_files $uri $uri/ /monitoreo_vmt/index.html;
    }
}
