server {
    listen 3008;
    root /usr/share/nginx/html;
    index index.html;

    # Evitar redirecciones con puerto
    port_in_redirect off;
    absolute_redirect off;

    location / {
        try_files $uri $uri/ /perfiles_especiales/index.html /index.html;
    }

    location /perfiles_especiales/ {
        alias /usr/share/nginx/html/perfiles_especiales/;
        try_files $uri $uri/ /perfiles_especiales/index.html;
    }


    # Proxies para el API (siguiendo tu ejemplo funcional)

    location /api/ {
        proxy_pass http://backend:8011/;
    }

    location /perfiles_especiales/api/ {
        proxy_pass http://backend:8011/;
    }
}
